apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment-albert
spec:
  selector:
    matchLabels:
      app: frontend-container-albert
  template:
    metadata:
      labels:
        app: frontend-container-albert
    spec:
      containers:
        - name: frontend-container-albert
          image: 319923562419.dkr.ecr.ap-southeast-2.amazonaws.com/lumina-images/frontend
          env:
            - name: BACKENDAPI
              value: api.albert.lumina.earth
          resources:
            limits:
              memory: "500Mi"
              cpu: "0.2"
          ports:
            - containerPort: 80
            - containerPort: 33440
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service-albert
spec:
  selector:
    app: frontend-container-albert
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress-albert
  namespace: albert
spec:
  rules:
    - host: albert.lumina.earth
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service-albert
                port:
                  number: 80
# - host: api.albert.lumina.earth
#   http:
#     paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: backend-service-albert
#             port:
#               number: 80
# ---
# # Custom Ingress Service
# apiVersion: v1
# kind: Service
# metadata:
#   name: drawbridge-ingress-service
# spec:
#   selector:
#     app: drawbridge-ingress-service
#   ports:
#     - name: http
#       protocol: TCP
#       port: 80
#       targetPort: 80
#     - name: https
#       protocol: TCP
#       port: 443
#       targetPort: 443
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: drawbridge-ingress-service
# spec:
#   selector:
#     matchLabels:
#       app: drawbridge-ingress-service
#   template:
#     metadata:
#       labels:
#         app: drawbridge-ingress-service
#     spec:
#       containers:
#         - name: drawbridge-ingress-service
#           image: albertmashy/drawbridge-ingress:0.4
#           resources:
#             limits:
#               memory: "30Mi"
#               cpu: "0.2"
#           ports:
#             - containerPort: 80
#             - containerPort: 443
