
kind: Namespace
apiVersion: v1
metadata:
  name: production
  labels:
    name: production
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: circle-ci-role
  namespace: production
rules:
  - apiGroups:
      - networking.k8s.io/v1
      - ""
      - apps
    resources:
      - ingresses
      - pods
      - daemonsets
      - deployments
      - services
    verbs:
      - get
      - list
      - update
      - patch
      - watch
      - create
      - delete
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: circle-ci-role-binding
  namespace: production
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: circle-ci-role
subjects:
  - kind: User
    name: lumina-circle-ci
    namespace: production